server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost/spring
    username: root
    password: jagaban##
    initialization-mode: always

jwkSetUri: http://localhost:8180/auth/realms/SpringSecurityInAction/protocol/openid-connect/certs
claimAud: fitnessapp